### ISSUE TITLE
Invoice status "paid" with incomplete payment

### ISSUE THREAD

**Issue by alejobit** [CSBill/CSBill#61]
Sorry for my English, I noticed that when multiple payments are made on an invoice, this is labeled as "paid" without having completed the full amount that should be paid.

**Comment by pierredup** [comment]
@alejobit Which version are you using? Also does it happen with any payment method or only when using a specific one?

**Comment by alejobit** [comment]
@pierredup I just cloned the latest master branch a day ago. I used cash and bank transfer payment method. It also happens in the demo page.

**Comment by pierredup** [comment]
Thanks @alejobit

**Comment by alejobit** [comment]
Thanks to you for sharing this application, I'll keep trying and learning more about it.
