### ISSUE TITLE
nginx error 502 Bad Gateway on /app_dev.php/

### ISSUE THREAD

**Issue by ibasaw** [CSBill/CSBill#75]
in prod, no problem, but in dev, got nginx error 502

never got this problem before, all my websites works in dev with my nginx version 1.2.1

**Comment by pierredup** [comment]
@ibasaw Can you please check in the Nginx log files for any errors?
Normally the main cause of this could be permissions on the cache directories, or a fatal error in the code somewhere. But the log files should have some indication on what caused the issue

**Comment by ibasaw** [comment]
upstream sent too big header while reading response header from upstream

**Comment by pierredup** [comment]
Can you please checkout the latest version on master and see if it fixes the issue

**Comment by ibasaw** [comment]
ok, this was that. thank you !
